" 
" My custom Vim settings
" 

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

"-------------------------------------------

"
" Visual/theme settings:
"

set guifont=Consolas:h11
color desert
"color abra
" (Good color schemes: darkblue, desert, slate)

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
let &guioptions = substitute(&guioptions, "t", "", "g")

" Keep cursor a few lines away from edges
set scrolloff=3

" Show the cursor position all the time
set ruler

" Show line numbers
set number

" Indent new line same as previous
set autoindent

" Highlight current line
set cursorline

" Show matching parens/brackets
set showmatch

" Highlight column 80
set colorcolumn=80

"-------------------------------------------

"
" Key mappings
"

" <Enter> to enter insert mode after cursor
nnoremap <CR> a

" <Ctrl-Space> to autocomplete from words in file
inoremap <C-Space> <C-x><C-n>

" <Shift-Enter> to return to normal mode
inoremap <S-CR> <Esc>


"-------------------------------------------

"
" Editing settings
"

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Tabbing: always replace with 4 spaces
:set tabstop=4 shiftwidth=4 softtabstop=4 expandtab

" Command autocompletion:
:set wildmode=longest:full
:set wildmenu

" Insert autocompletion:
:set completeopt=longest,menu

" Keep backup file
"if has("vms")
"  set nobackup
"else
"  set backup
"endif

" Switch to window if buffer already open
set switchbuf=useopen

" Open splits below and to the right
set splitbelow
set splitright

" No backup files.
set nobackup
set nowritebackup
set noswapfile

" Keep 50 lines of command line history
set history=50

" Display incomplete commands
set showcmd

" Do incremental searching
set incsearch

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
  syntax on
endif

" Maximize if using GUI
if has("gui_running")
    au GUIEnter * simalt ~x
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")
  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on
  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!
  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif
  augroup END
else
  set autoindent		" always set autoindenting on
endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif


set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

